# Generated by Django 4.1.7 on 2023-04-11 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="season",
            options={"ordering": ["parent", "number"]},
        ),
        migrations.RenameField(
            model_name="season",
            old_name="media",
            new_name="parent",
        ),
    ]
