# Generated by Django 4.2 on 2023-06-21 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tv",
            name="progress",
        ),
    ]
