# Generated by Django 4.1.4 on 2023-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
