# Generated by Django 4.2 on 2023-07-01 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="tv_season",
            new_name="related_season",
        ),
    ]
