# Generated by Django 4.1.5 on 2023-02-02 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
