# Generated by Django 4.1.7 on 2023-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="season",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("tv", "TV"),
                    ("movie", "Movie"),
                ],
                max_length=10,
            ),
        ),
    ]
