# Generated by Django 4.2 on 2023-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="progress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manga",
            name="progress",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
