# Generated by Django 4.2 on 2023-09-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="manga",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="season",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="tv",
            name="image",
            field=models.URLField(),
        ),
    ]
