# Generated by Django 4.2.5 on 2024-01-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_anime_image_alter_manga_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                    ("Planning", "Planning"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                    ("Planning", "Planning"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                    ("Planning", "Planning"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                    ("Planning", "Planning"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
    ]
