# Generated by Django 4.1.4 on 2023-02-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_media_end_date_media_start_date_season_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="score",
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="score",
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
