# Generated by Django 4.2 on 2023-07-13 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_tv_season_episode_related_season"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="season",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="anime",
            unique_together={("media_id", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("related_season", "episode_number")},
        ),
        migrations.AlterUniqueTogether(
            name="manga",
            unique_together={("media_id", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="movie",
            unique_together={("media_id", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("media_id", "season_number", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="tv",
            unique_together={("media_id", "user")},
        ),
    ]
