# Generated by Django 4.2.5 on 2024-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_anime_status_alter_manga_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
