# Generated by Django 4.2 on 2023-05-06 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_episode_title_remove_season_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="watched",
        ),
    ]
