# Generated by Django 4.2.5 on 2024-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_movie_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
