# Generated by Django 4.2 on 2023-05-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_episode_watched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="app.season",
            ),
        ),
    ]
