# Generated by Django 4.2.5 on 2024-02-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_tv_end_date_tv_progress_tv_start_date_tv_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="season",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="tv",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="tv",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="tv",
            name="start_date",
        ),
        migrations.AddField(
            model_name="season",
            name="related_tv",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="app.tv",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="anime",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="tv",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("related_tv", "season_number")},
        ),
    ]
