# Generated by Django 5.2.2 on 2025-10-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_completed_manually'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbook',
            name='completed_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='completion_diary_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='item',
            field=models.ForeignKey(limit_choices_to={'media_type__in': ['movie', 'tv', 'season', 'book']}, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
