# Generated by Django 5.2.2 on 2025-11-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_historicalbook_completed_manually_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='item',
            field=models.ForeignKey(limit_choices_to={'media_type__in': ['movie', 'tv', 'season', 'book', 'game']}, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
