# Generated by Django 5.0.3 on 2024-03-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='revisits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='revisits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='revisits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='revisits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='revisits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tv',
            name='revisits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
