# Generated by Django 5.0.3 on 2024-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_revisits_anime_repeats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Repeating', 'Repeating'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=12),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Repeating', 'Repeating'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=12),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Repeating', 'Repeating'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=12),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Repeating', 'Repeating'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=12),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Repeating', 'Repeating'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=12),
        ),
        migrations.AlterField(
            model_name='tv',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Repeating', 'Repeating'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=12),
        ),
    ]
