# Generated by Django 5.0.3 on 2024-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_anime_status_alter_game_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['related_season', 'episode_number']},
        ),
        migrations.RemoveField(
            model_name='season',
            name='repeats',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='repeats',
        ),
        migrations.AddField(
            model_name='episode',
            name='repeats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
