# Generated by Django 5.0.6 on 2024-07-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_user_customlist_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomListItem',
        ),
        migrations.DeleteModel(
            name='CustomList',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
