# Generated by Django 5.0.6 on 2024-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_customlistitem_custom_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.PositiveIntegerField()),
                ('media_type', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('season_number', models.PositiveIntegerField(null=True)),
                ('episode_number', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['media_id'],
                'unique_together': {('media_id', 'media_type', 'season_number', 'episode_number')},
            },
        ),
    ]
