# Generated by Django 5.0.6 on 2024-08-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_episode_options_alter_anime_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('season', 'Season'), ('episode', 'Episode'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game')], max_length=10),
        ),
    ]
