# Generated by Django 5.1 on 2024-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_item_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
