# Generated by Django 5.1.1 on 2024-10-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('season', 'Season'), ('episode', 'Episode'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game')], default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='season_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
