# Generated by Django 5.2 on 2025-05-20 17:52

from django.db import migrations

def enable_import_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(name__startswith='Import ').update(enabled=True)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_anime_end_date_alter_anime_start_date_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RunPython(enable_import_tasks, reverse_code=migrations.RunPython.noop),
    ]