# Generated by Django 5.2 on 2025-06-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_anime_options_alter_basicmedia_options_and_more'),
    ]

    operations = [
    ]
