# Generated by Django 5.2 on 2025-06-13 14:55

from django.db import migrations

def update_repeating_status(apps, schema_editor):
    """Update Repeating status to In Progress for TV and Season models."""
    TV = apps.get_model("app", "TV")
    Season = apps.get_model("app", "Season")

    TV.objects.filter(status="Repeating").update(status="In progress")
    Season.objects.filter(status="Repeating").update(status="In progress")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_anime_options_alter_basicmedia_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_repeating_status, reverse_code=migrations.RunPython.noop),
    ]
