# Generated by Django 5.2.7 on 2025-10-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_migrate_simkl_periodoc_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="current_episode_progress",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="progress",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalanime",
            name="current_episode_progress",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="progress",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
