# Generated by Django 5.2.2 on 2025-07-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_historicaldiaryentry_diaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='item',
            field=models.ForeignKey(limit_choices_to={'media_type': 'movie'}, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
