# Generated by Django 5.2.2 on 2025-08-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_restrict_diary_to_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldiaryentry',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
