# Generated by Django 5.2.9 on 2026-02-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to fix boardgame value."""

    dependencies = [
        ("app", "0054_fix_movie_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Boardgame"),
                ],
                default="movie",
                max_length=10,
            ),
        ),
    ]
