# Generated by Django 5.2.11 on 2026-03-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_item_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='progress_unit',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='progress_unit',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
