# Generated by Django 5.2.12 on 2026-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_item_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_id',
            field=models.CharField(max_length=36),
        ),
    ]
