# Generated by Django 5.2.2 on 2025-09-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_migrate_simkl_periodoc_tasks'),
        ('app', '0055_diaryentry_is_rewatch'),
    ]

    operations = [
    ]
