# Generated by Django 5.2.12 on 2026-04-05 17:30

from django.db import migrations

MEDIA_TYPE_TV = "tv"
MEDIA_TYPE_SEASON = "season"
STATUS_COMPLETED = "Completed"
STATUS_IN_PROGRESS = "In progress"
STATUS_PLANNING = "Planning"


def reopen_completed_tv_with_new_seasons(apps, _):
    """Backfill completed TV entries when discovered seasons already exist."""
    Item = apps.get_model("app", "Item")
    Season = apps.get_model("app", "Season")
    TV = apps.get_model("app", "TV")

    completed_tvs = TV.objects.filter(
        status=STATUS_COMPLETED,
        item__media_type=MEDIA_TYPE_TV,
    ).select_related("item")

    for tv in completed_tvs.iterator():
        existing_seasons = Season.objects.filter(
            related_tv_id=tv.id,
        )

        if existing_seasons.exclude(status=STATUS_COMPLETED).exists():
            continue

        existing_season_numbers = set(
            existing_seasons.values_list("item__season_number", flat=True),
        )

        missing_season_items = list(
            Item.objects.filter(
                media_id=tv.item.media_id,
                source=tv.item.source,
                media_type=MEDIA_TYPE_SEASON,
                season_number__gt=0,
                event__isnull=False,
            )
            .exclude(season_number__in=existing_season_numbers)
            .distinct()
            .order_by("season_number")
        )

        if not missing_season_items:
            continue

        seasons_to_create = [
            Season(
                item=season_item,
                related_tv_id=tv.id,
                user_id=tv.user_id,
                status=STATUS_PLANNING,
            )
            for season_item in missing_season_items
        ]
        Season.objects.bulk_create(seasons_to_create)

        tv.status = STATUS_IN_PROGRESS
        TV.objects.bulk_update([tv], ["status"])


class Migration(migrations.Migration):
    """Backfill reopened TV shows when discovered seasons already exist."""

    dependencies = [
        ("events", "0014_delete_empty_content_number_comic_events"),
        ("app", "0056_alter_item_media_id"),
    ]

    operations = [
        migrations.RunPython(
            reopen_completed_tv_with_new_seasons,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
