# Generated by Django 5.2.12 on 2026-04-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_usermessage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usermessage",
            index=models.Index(
                fields=["user", "shown_at"],
                name="app_umsg_user_shown_idx",
            ),
        ),
    ]
