# Generated by Django 5.2.12 on 2026-04-14 12:00

from collections import defaultdict
from datetime import datetime
from zoneinfo import ZoneInfo

from django.db import migrations, transaction
from django.db.models import Exists, OuterRef
from django.utils import timezone

MEDIA_TYPE_TV = "tv"
STATUS_COMPLETED = "Completed"
STATUS_IN_PROGRESS = "In progress"
STATUS_PLANNING = "Planning"
BUGGY_MIGRATION_START = datetime(2026, 4, 6, 20, 0, tzinfo=ZoneInfo("UTC"))
BUGGY_MIGRATION_END = datetime(2026, 4, 14, 23, 0, tzinfo=ZoneInfo("UTC"))


def fix_reopened_completed_tv_seasons(apps, _):
    """Remove bad planning seasons created by 0057 and restore affected TVs."""
    Event = apps.get_model("events", "Event")
    HistoricalSeason = apps.get_model("app", "HistoricalSeason")
    HistoricalTV = apps.get_model("app", "HistoricalTV")
    Season = apps.get_model("app", "Season")
    TV = apps.get_model("app", "TV")

    now = timezone.now()
    season_history = HistoricalSeason.objects.filter(id=OuterRef("id"))
    future_events = Event.objects.filter(
        item_id=OuterRef("item_id"),
        datetime__gte=now,
    )

    # 0057 created plain Planning seasons without history. If those seasons also
    # have no future events and were created during the v0.25.1 release window
    # (April 6, 2026 22:00 UTC+2 to April 15, 2026 01:00 UTC+2), they are very
    # likely the bogus backfill we want to remove rather than a legitimate
    # upcoming season.
    bogus_seasons = list(
        Season.objects
        .filter(
            status=STATUS_PLANNING,
            related_tv__status=STATUS_IN_PROGRESS,
            related_tv__item__media_type=MEDIA_TYPE_TV,
            created_at__gte=BUGGY_MIGRATION_START,
            created_at__lte=BUGGY_MIGRATION_END,
        )
        .annotate(
            has_history=Exists(season_history),
            has_future_events=Exists(future_events),
        )
        .filter(
            has_history=False,
            has_future_events=False,
        )
        .select_related("related_tv", "user")
    )
    if not bogus_seasons:
        return

    seasons_by_tv_id = defaultdict(list)
    for season in bogus_seasons:
        seasons_by_tv_id[season.related_tv_id].append(season)

    with transaction.atomic():
        Season.objects.filter(
            id__in=[season.id for season in bogus_seasons],
        ).delete()

        for tv_id, tv_seasons in seasons_by_tv_id.items():
            tv = tv_seasons[0].related_tv
            latest_history = (
                HistoricalTV.objects
                .filter(id=tv.id)
                .order_by("-history_date", "-history_id")
                .first()
            )
            if not latest_history or latest_history.status != STATUS_COMPLETED:
                continue

            # Users often had the parent TV marked completed without tracking
            # seasons individually, so once the bogus 0057 seasons are gone we
            # can safely restore the parent TV to completed.
            if tv.status != STATUS_IN_PROGRESS:
                continue

            tv.status = STATUS_COMPLETED
            TV.objects.filter(pk=tv.pk).update(status=tv.status)


class Migration(migrations.Migration):
    """Repair bad planning seasons created for already completed shows."""

    dependencies = [
        ("events", "0014_delete_empty_content_number_comic_events"),
        ("app", "0059_usermessage_user_shown_idx"),
    ]

    operations = [
        migrations.RunPython(
            fix_reopened_completed_tv_seasons,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
