# Generated by Django 5.2.11 on 2026-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_fix_reopened_completed_tv_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicmedia',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comic',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalanime',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbasicmedia',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalboardgame',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcomic',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmanga',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalseason',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltv',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tv',
            name='hide_from_home',
            field=models.BooleanField(default=False),
        ),
    ]
