# Generated by Django 5.2.7 on 2026-06-15 18:25

from django.db import migrations, models


def remove_boardgame_items(apps, schema_editor):
    """Delete board game data before removing the media type constraints."""
    Item = apps.get_model("app", "Item")
    BoardGame = apps.get_model("app", "BoardGame")
    HistoricalBoardGame = apps.get_model("app", "HistoricalBoardGame")

    BoardGame.objects.all().delete()
    HistoricalBoardGame.objects.all().delete()
    Item.objects.filter(media_type="boardgame").delete()
    Item.objects.filter(source="bgg").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_episode_item_not_null'),
    ]

    operations = [
        migrations.RunPython(remove_boardgame_items, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='boardgame',
            name='item',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalboardgame',
            name='history_user',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='app_item_source_valid',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='app_item_media_type_valid',
        ),
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic')], default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('igdb', 'Internet Game Database'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('comicvine', 'Comic Vine'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['tmdb', 'mal', 'mangaupdates', 'igdb', 'openlibrary', 'hardcover', 'comicvine', 'manual'])), name='app_item_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['tv', 'season', 'episode', 'movie', 'anime', 'manga', 'game', 'book', 'comic'])), name='app_item_media_type_valid'),
        ),
        migrations.DeleteModel(
            name='BoardGame',
        ),
        migrations.DeleteModel(
            name='HistoricalBoardGame',
        ),
    ]
