# Generated by Django 5.2.13 on 2026-05-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_customlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customlink",
            name="object_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]
