# Generated by Django 5.2.13 on 2026-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_episode_item_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='basicmedia',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='comic',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='manga',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='season',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tv',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both')], default='', max_length=20),
        ),
    ]
