# Generated by Django 5.2.13 on 2026-05-11 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_alter_customlink_object_id"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("normalized_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaggedMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_media",
                        to="app.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user", "name"], name="app_tag_user_name_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["user", "normalized_name"], name="app_tag_user_norm_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "normalized_name"),
                name="unique_tag_per_user_normalized_name",
            ),
        ),
        migrations.AddIndex(
            model_name="taggedmedia",
            index=models.Index(
                fields=["content_type", "object_id"], name="app_tmedia_target_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taggedmedia",
            index=models.Index(fields=["user"], name="app_tmedia_user_idx"),
        ),
        migrations.AddIndex(
            model_name="taggedmedia",
            index=models.Index(fields=["tag"], name="app_tmedia_tag_idx"),
        ),
        migrations.AddConstraint(
            model_name="taggedmedia",
            constraint=models.UniqueConstraint(
                fields=("user", "tag", "content_type", "object_id"),
                name="unique_tagged_media_per_target",
            ),
        ),
    ]
