# Generated by Django 5.2.13 on 2026-06-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_anime_hide_from_home_basicmedia_hide_from_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicmedia',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comic',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='manga',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='season',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='hide_from_home',
            field=models.CharField(blank=True, choices=[('', 'Not Hidden'), ('in_progress', 'Hide from In Progress'), ('both', 'Hide from Both (In Progress and Planning)')], default='', max_length=20),
        ),
    ]
