# Generated by Django 5.2.13 on 2026-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_experience_experiencevisit_historicalexperience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.URLField(max_length=500),
        ),
    ]
