# Generated by Django 5.2.16 on 2026-09-25 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tmdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.DecimalValidator(3, 1), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='item',
            name='tmdb_rating_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
