# Generated by Django 5.2.14 on 2026-06-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_custombackdroppreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovie',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
