# Generated by Django 5.2.16 on 2026-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stream_availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='stream_availability_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
