# Generated by Django 5.2.16 on 2026-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseason',
            name='rewatch_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='rewatch_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseason',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Rewatching', 'Rewatching')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltv',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Rewatching', 'Rewatching')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Rewatching', 'Rewatching')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Rewatching', 'Rewatching')], default='Completed', max_length=20),
        ),
    ]
