# Generated by Django 5.2 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_restore_tz_shifted_media_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltv",
            name="rewatch_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tv",
            name="rewatch_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
