# Generated by Codex on 2026-06-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_media_likes(apps, schema_editor):
    MediaLike = apps.get_model("app", "MediaLike")
    Movie = apps.get_model("app", "Movie")
    DiaryEntry = apps.get_model("app", "DiaryEntry")

    liked_at_by_pair = {}
    for movie in Movie.objects.filter(liked=True).only("user_id", "item_id", "created_at").iterator():
        key = (movie.user_id, movie.item_id)
        liked_at_by_pair[key] = max(liked_at_by_pair.get(key, movie.created_at), movie.created_at)

    diary_rows = DiaryEntry.objects.filter(liked=True).only("user_id", "item_id", "created_at")
    if hasattr(DiaryEntry, "updated_at"):
        diary_rows = diary_rows.only("user_id", "item_id", "created_at", "updated_at")
    for entry in diary_rows.iterator():
        key = (entry.user_id, entry.item_id)
        liked_at = getattr(entry, "updated_at", None) or entry.created_at
        liked_at_by_pair[key] = max(liked_at_by_pair.get(key, liked_at), liked_at)

    MediaLike.objects.bulk_create(
        [
            MediaLike(user_id=user_id, item_id=item_id, created_at=created_at)
            for (user_id, item_id), created_at in liked_at_by_pair.items()
        ],
        ignore_conflicts=True,
        batch_size=1000,
    )


def delete_backfilled_media_likes(apps, schema_editor):
    apps.get_model("app", "MediaLike").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0065_historicalmovie_liked_movie_liked"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_likes",
                        to="app.item",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "-created_at", "-id"], name="app_mediali_user_id_981f21_idx"),
                    models.Index(fields=["item", "-created_at"], name="app_mediali_item_id_c3edb8_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "item"), name="app_medialike_unique_user_item"),
                ],
            },
        ),
        migrations.RunPython(backfill_media_likes, delete_backfilled_media_likes),
    ]
