# Generated by Django 5.2.14 on 2026-06-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_animeseriesviewmembership_display_alternative_title_en_and_v3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeseriesviewmembership",
            name="projection_version",
            field=models.CharField(default="franchise_root_v4", max_length=30),
        ),
    ]
