# Generated by Django 5.2.13 on 2026-05-25 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_alter_item_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "TV Show"),
                            ("season", "TV Season"),
                            ("episode", "Episode"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("game", "Game"),
                            ("book", "Book"),
                            ("comic", "Comic"),
                            ("boardgame", "Boardgame"),
                            ("experience", "Experience"),
                        ],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["user", "media_type"], name="app_catlink_user_type_idx"
                    )
                ],
            },
        ),
    ]
