# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


DIARY_MEDIA_TYPES = [
    "movie",
    "tv",
    "season",
    "episode",
    "anime",
    "manga",
    "book",
    "game",
    "comic",
]


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_medialike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="item",
            field=models.ForeignKey(
                limit_choices_to={"media_type__in": DIARY_MEDIA_TYPES},
                on_delete=django.db.models.deletion.CASCADE,
                to="app.item",
            ),
        ),
    ]
