# Generated by Codex on 2026-06-01

from django.db import migrations, models


def set_existing_books_to_pages(apps, _schema_editor):
    """Preserve existing book progress semantics by treating it as pages."""
    Book = apps.get_model("app", "Book")
    HistoricalBook = apps.get_model("app", "HistoricalBook")
    Book.objects.update(progress_unit="pages")
    HistoricalBook.objects.update(progress_unit="pages")


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_alter_anime_status_alter_basicmedia_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="progress_unit",
            field=models.CharField(
                choices=[
                    ("pages", "Pages"),
                    ("chapters", "Chapters"),
                    ("percent", "Percent"),
                    ("hours", "Hours"),
                ],
                default="chapters",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="progress_unit",
            field=models.CharField(
                choices=[
                    ("pages", "Pages"),
                    ("chapters", "Chapters"),
                    ("percent", "Percent"),
                    ("hours", "Hours"),
                ],
                default="chapters",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            set_existing_books_to_pages,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
