# Generated by Django 5.2.13 on 2026-06-07 15:43

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0068_book_progress_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="uploaded_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app.models.manual_item_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    app.models.validate_manual_item_image_size,
                ],
            ),
        ),
    ]
