version: "3"
services:
  yamtarr:
    container_name: yamtarr
    build:
      context: .
    environment:
      - ALLOWED_HOSTS=192.168.1.1, yamtarr.domain.com
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db:/app/db
      - static:/app/static
      - media:/app/media

  yamtarr-gateway:
    container_name: yamtarr-gateway
    build:
      context: ./gateway
    volumes:
      - static:/vol/static
      - media:/vol/media
    ports:
      - "8080:8080"
    depends_on:
      - yamtarr

volumes:
  static:
  media: