services:
  yamtrack:
    container_name: yamtrack
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=Europe/Berlin
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./db:/yamtrack/db
    ports:
      - "8036:8000"

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
