version: "3"
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - TMDB_API=TMDB_API_KEY
      - MAL_API=MAL_API_KEY
      - DB_HOST=db
      - DB_NAME=yamtrack
      - DB_USER=yamtrack
      - DB_PASS=yamtrack
      - DB_PORT=5432
    ports:
      - "8000:8000"

  db:
    image: docker.io/library/postgres:15-alpine
    container_name: yamtrack_db
    environment:
      - POSTGRES_DB=yamtrack
      - POSTGRES_USER=yamtrack
      - POSTGRES_PASSWORD=yamtrack
      - TZ=Europe/Madrid
      - PGTZ=Europe/Madrid
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
