services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=Europe/Berlin
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
      - YAMTRACK_INTERNAL_PORT=${YAMTRACK_INTERNAL_PORT:-8000}
    volumes:
      - ./db:/yamtrack/db
    ports:
      - "8000:${YAMTRACK_INTERNAL_PORT:-8000}"

  redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
