site_name: Yamtrack Documentation
site_url: https://FuzzyGrim.github.io/Yamtrack/
site_author: FuzzyGrim
site_description: >-
  Yamtrack is a self hosted media tracker for movies, tv shows, 
  anime, manga, video games, books, comics, and board games.
repo_name: FuzzyGrim/Yamtrack
repo_url: https://github.com/FuzzyGrim/Yamtrack
copyright: Copyright &copy; 2022 - 2026 FuzzyGrim
edit_uri: edit/dev/docs/
nav:
  - Home: index.md
  - Installation: installation.md
  - Environment Variables: env-variables.md
  - Media Imports: media-imports.md
  - Social Auth: social-auth.md
  - Administration: administration.md
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search:
      lang:
        - en
  - include-markdown
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: FuzzyGrim/Yamtrack
      branch: dev
  - git-authors:
      show_email_address: false
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FuzzyGrim/Yamtrack
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
watch:
  - docs
