[project]
name = "yamtrack"
version = "0.26.1"
description = "A self hosted media tracker."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "aiohttp~=3.14.3",
  "apprise~=1.12.0",
  "beautifulsoup4~=4.15.0",
  "celery~=5.6.3",
  "croniter~=6.2.4",
  "defusedxml~=0.7.1",
  "django~=5.2.16",
  "django-allauth[socialaccount]~=65.16.1",
  "django-celery-beat~=2.9.0",
  "django-celery-results~=2.6.0",
  "django-debug-toolbar~=6.3.0",
  "django-health-check[celery,redis]~=4.4.1",
  "django-model-utils~=5.0.0",
  "django-redis~=6.0.0",
  "django-select2~=8.4.8",
  "django-simple-history~=3.13.0",
  "django-widget-tweaks~=1.5.1",
  "gunicorn~=26.0.0",
  "icalendar~=7.2.2",
  "pillow~=12.3.0",
  "psycopg[binary,pool]~=3.3.4",
  "python-decouple~=3.8",
  "redis[hiredis]~=7.4.0",
  "requests~=2.34.2",
  "requests-ratelimiter~=0.10.0",
  "supervisor~=4.3.0",
  "unidecode~=1.4.0",
]

[dependency-groups]
lint = [
  "django-upgrade~=1.31.1",
  "djlint~=1.44.1",
  "pre-commit~=4.6.1",
  "ruff~=0.16.1",
]
test = [
  "coverage~=7.15.4",
  "fakeredis[lua]~=2.35.1",
  "pytest-django~=4.13.0",
  "pytest-playwright~=0.8.0",
  "tblib~=3.2.2",
]
dev = [
  {include-group = "lint"},
  {include-group = "test"},
]
docs = [
  "zensical==0.0.53",
  "mike @ git+https://github.com/squidfunk/mike.git",
]

[tool.uv]
package = false

[tool.ruff]
target-version = "py312"
extend-exclude = ["migrations"]
force-exclude = true

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN", "PT", "PD", "D100", "D104", "RUF012", "SLF001", "COM812", "CPY001"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.ruff.lint.pylint]
max-args = 7
max-positional-args = 6

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.djlint]
custom_blocks = "element,slot,setvar"
preserve_blank_lines = true
ignore = "H006,H021"
indent = 2

[tool.coverage.run]
concurrency = ["multiprocessing"]
omit = ["*/migrations/*", "*/tests/*", "*/__init__.py", "*/admin.py"]
