[tool.ruff]
target-version = "py311"
extend-exclude = ["migrations"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN", "PT", "D100", "D104", "RUF012"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.ruff.lint.pydocstyle]
convention = "pep257"


[tool.djlint]
preserve_blank_lines = true
ignore = "H006"
