[supervisord]
nodaemon=true
logfile=/tmp/supervisord.conf

[program:nginx]
command=nginx -c /etc/nginx/nginx.conf -g "daemon off;"
priority=1

[program:gunicorn]
command=gunicorn --control-socket /tmp/gunicorn.ctl --config python:config.gunicorn config.wsgi:application
priority=5

[program:celery]
command=sh -c 'if [ "${ENV_DEBUG:-False}" = "True" ]; then LOGLEVEL=DEBUG; else LOGLEVEL=INFO; fi; celery --app config worker --loglevel $LOGLEVEL --without-mingle --without-gossip'
stopasgroup=true
stopwaitsecs=60
priority=10

[program:celery-beat]
command=sh -c 'if [ "${ENV_DEBUG:-False}" = "True" ]; then LOGLEVEL=DEBUG; else LOGLEVEL=INFO; fi; celery --app config beat --loglevel $LOGLEVEL'
stopasgroup=true
priority=15
