# Generated by Django 5.2.14 on 2026-06-23 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterboxdUriCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(unique=True)),
                ('tmdb_id', models.CharField(max_length=36)),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic')], default='movie', max_length=10)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.CharField(blank=True, choices=[('scrape', 'Scrape'), ('imdb', 'IMDb'), ('search', 'Search')], default='', max_length=10)),
            ],
            options={
                'ordering': ['uri'],
            },
        ),
    ]
