# Generated by Django 5.2.2 on 2025-10-08 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_initial'),
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customlistitem',
            name='custom_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.customlist'),
        ),
        migrations.AddField(
            model_name='customlistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='custom_lists', through='lists.CustomListItem', to='app.item'),
        ),
        migrations.AddConstraint(
            model_name='customlistitem',
            constraint=models.UniqueConstraint(fields=('item', 'custom_list'), name='lists_customlistitem_unique_item_list'),
        ),
    ]
