# Generated by Django 5.2.14 on 2026-06-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_customlist_visibility_slug_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customlistitem',
            options={'ordering': [models.OrderBy(models.F('position'), nulls_last=True), 'date_added']},
        ),
        migrations.AddField(
            model_name='customlist',
            name='import_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customlistitem',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
