# Generated by Django 5.2.14 on 2026-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_customlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public lists are visible to all users'),
        ),
    ]
