# Generated by Codex on 2026-06-24

from django.db import migrations, models


def backfill_ranked_lists(apps, schema_editor):
    CustomList = apps.get_model("lists", "CustomList")
    CustomList.objects.filter(customlistitem__position__isnull=False).distinct().update(
        is_ranked=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_customlistitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customlist",
            name="is_ranked",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_ranked_lists, migrations.RunPython.noop),
    ]
