# Generated by Django 5.0.3 on 2024-04-17 10:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# users.migrations.0006_alter_user_anime_layout_alter_user_manga_layout_and_more

class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_alter_user_last_search_type'), ('users', '0003_user_default_layout'), ('users', '0004_user_editable'), ('users', '0005_remove_user_default_layout_user_anime_layout_and_more'), ('users', '0006_alter_user_anime_layout_alter_user_manga_layout_and_more'), ('users', '0007_remove_user_editable_user_is_demo'), ('users', '0008_user_game_layout_alter_user_last_search_type')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_search_type', models.CharField(choices=[('tv', 'tv'), ('movie', 'movie'), ('anime', 'anime'), ('manga', 'manga')], default='tv', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('editable', models.BooleanField(default=True)),
                ('anime_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20)),
                ('manga_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20)),
                ('movie_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('season_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('tv_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='editable',
        ),
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='game_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'tv'), ('movie', 'movie'), ('anime', 'anime'), ('manga', 'manga'), ('game', 'game')], default='tv', max_length=10),
        ),
    ]
