# Generated by Django 5.2.2 on 2025-10-08 22:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_demo', models.BooleanField(default=False)),
                ('last_search_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic')], default='tv', max_length=10)),
                ('home_sort', models.CharField(choices=[('upcoming', 'Upcoming'), ('recent', 'Recent'), ('completion', 'Completion'), ('episodes_left', 'Episodes Left'), ('title', 'Title')], default='upcoming', max_length=20)),
                ('tv_enabled', models.BooleanField(default=True)),
                ('tv_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('tv_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('tv_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('season_enabled', models.BooleanField(default=True)),
                ('season_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('season_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('season_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('movie_enabled', models.BooleanField(default=True)),
                ('movie_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('movie_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('movie_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('anime_enabled', models.BooleanField(default=True)),
                ('anime_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20)),
                ('anime_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('anime_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('manga_enabled', models.BooleanField(default=True)),
                ('manga_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20)),
                ('manga_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('manga_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('game_enabled', models.BooleanField(default=True)),
                ('game_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('game_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('game_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('book_enabled', models.BooleanField(default=True)),
                ('book_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('book_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('book_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('comic_enabled', models.BooleanField(default=True)),
                ('comic_layout', models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('comic_sort', models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('comic_status', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('hide_from_search', models.BooleanField(default=True)),
                ('calendar_layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20)),
                ('lists_sort', models.CharField(choices=[('last_item_added', 'Last Item Added'), ('name', 'Name'), ('items_count', 'Items Count'), ('newest_first', 'Newest First')], default='last_item_added', max_length=20)),
                ('list_detail_sort', models.CharField(choices=[('date_added', 'Date Added'), ('title', 'Title'), ('media_type', 'Media Type')], default='date_added', max_length=20)),
                ('notification_urls', models.TextField(blank=True, help_text='Apprise URLs for notifications')),
                ('release_notifications_enabled', models.BooleanField(default=True, help_text='Receive notifications for recently released media')),
                ('daily_digest_enabled', models.BooleanField(default=True, help_text='Receive a daily digest of upcoming releases')),
                ('token', models.CharField(default=users.models.generate_token, help_text='Token for external integrations', max_length=32, unique=True)),
                ('plex_usernames', models.TextField(blank=True, help_text='Comma-separated list of Plex usernames for webhook matching')),
                ('bio', models.TextField(blank=True, help_text='User bio/description (max 500 characters)', max_length=500)),
                ('pronouns', models.CharField(blank=True, help_text='User preferred pronouns (e.g. she/her, he/him, they/them)', max_length=50)),
                ('location', models.CharField(blank=True, help_text='User location (city, country)', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('hof_anime', models.ForeignKey(blank=True, help_text='Hall of Fame anime', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item')),
                ('hof_book', models.ForeignKey(blank=True, help_text='Hall of Fame book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item')),
                ('hof_comic', models.ForeignKey(blank=True, help_text='Hall of Fame comic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item')),
                ('hof_game', models.ForeignKey(blank=True, help_text='Hall of Fame game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item')),
                ('hof_manga', models.ForeignKey(blank=True, help_text='Hall of Fame manga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item')),
                ('hof_movie', models.ForeignKey(blank=True, help_text='Hall of Fame movie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item')),
                ('hof_tv', models.ForeignKey(blank=True, help_text='Hall of Fame TV show', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item')),
                ('notification_excluded_items', models.ManyToManyField(blank=True, help_text='Items excluded from notifications', related_name='excluded_by_users', to='app.item')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
                'constraints': [models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'movie', 'anime', 'manga', 'game', 'book', 'comic'])), name='last_search_type_valid'), models.CheckConstraint(condition=models.Q(('home_sort__in', ['upcoming', 'recent', 'completion', 'episodes_left', 'title'])), name='home_sort_valid'), models.CheckConstraint(condition=models.Q(('tv_layout__in', ['grid', 'table'])), name='tv_layout_valid'), models.CheckConstraint(condition=models.Q(('season_layout__in', ['grid', 'table'])), name='season_layout_valid'), models.CheckConstraint(condition=models.Q(('movie_layout__in', ['grid', 'table'])), name='movie_layout_valid'), models.CheckConstraint(condition=models.Q(('anime_layout__in', ['grid', 'table'])), name='anime_layout_valid'), models.CheckConstraint(condition=models.Q(('manga_layout__in', ['grid', 'table'])), name='manga_layout_valid'), models.CheckConstraint(condition=models.Q(('game_layout__in', ['grid', 'table'])), name='game_layout_valid'), models.CheckConstraint(condition=models.Q(('book_layout__in', ['grid', 'table'])), name='book_layout_valid'), models.CheckConstraint(condition=models.Q(('tv_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='tv_sort_valid'), models.CheckConstraint(condition=models.Q(('season_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='season_sort_valid'), models.CheckConstraint(condition=models.Q(('movie_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='movie_sort_valid'), models.CheckConstraint(condition=models.Q(('anime_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='anime_sort_valid'), models.CheckConstraint(condition=models.Q(('manga_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='manga_sort_valid'), models.CheckConstraint(condition=models.Q(('game_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='game_sort_valid'), models.CheckConstraint(condition=models.Q(('book_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='book_sort_valid'), models.CheckConstraint(condition=models.Q(('calendar_layout__in', ['grid', 'list'])), name='calendar_layout_valid'), models.CheckConstraint(condition=models.Q(('lists_sort__in', ['last_item_added', 'name', 'items_count', 'newest_first'])), name='lists_sort_valid'), models.CheckConstraint(condition=models.Q(('list_detail_sort__in', ['date_added', 'title', 'media_type'])), name='list_detail_sort_valid'), models.CheckConstraint(condition=models.Q(('tv_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='tv_status_valid'), models.CheckConstraint(condition=models.Q(('season_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='season_status_valid'), models.CheckConstraint(condition=models.Q(('movie_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='movie_status_valid'), models.CheckConstraint(condition=models.Q(('anime_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='anime_status_valid'), models.CheckConstraint(condition=models.Q(('manga_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='manga_status_valid'), models.CheckConstraint(condition=models.Q(('game_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='game_status_valid'), models.CheckConstraint(condition=models.Q(('book_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='book_status_valid')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
