# Generated by Django 4.2.5 on 2024-02-12 21:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_last_search_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_layout",
            field=models.JSONField(default="users.models.get_default_layout"),
        ),
    ]
