# Generated by Django 5.0.2 on 2024-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_default_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
