# Generated by Django 5.0.2 on 2024-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_default_layout_user_anime_layout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anime_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
    ]
