# Generated by Django 5.0.3 on 2024-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_editable_user_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'tv'), ('movie', 'movie'), ('anime', 'anime'), ('manga', 'manga'), ('game', 'game')], default='tv', max_length=10),
        ),
    ]
