# Generated by Django 5.2.2 on 2025-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_update_repeating_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='home_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='home_sort',
            field=models.CharField(choices=[('recent', 'Recent'), ('upcoming', 'Upcoming'), ('completion', 'Completion'), ('episodes_left', 'Episodes Left'), ('title', 'Title')], default='upcoming', max_length=20),
        ),
    ]
