# Generated by Django 5.2.2 on 2025-07-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_fix_null_history_users'),
        ('users', '0036_update_repeating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hof_anime',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame anime', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hof_book',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hof_comic',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame comic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hof_game',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hof_manga',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame manga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hof_movie',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame movie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hof_tv',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame TV show', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
    ]
