# Generated by Django 5.2.2 on 2025-09-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_user_home_sort_valid_alter_user_home_sort'),
        ('users', '0037_user_hof_anime_user_hof_book_user_hof_comic_and_more'),
    ]

    operations = [
    ]
