# Generated by Django 5.2.2 on 2025-08-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_migrate_simkl_periodoc_tasks"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0037_remove_user_home_sort_valid_alter_user_home_sort"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="tv_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="season_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="movie_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="anime_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="manga_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="game_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="book_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="anime_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="book_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comic_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="game_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="manga_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="movie_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="season_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tv_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("time_left", "Time Left"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "home_sort__in",
                        ["recent", "upcoming", "completion", "episodes_left", "title"],
                    )
                ),
                name="home_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tv_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "time_left",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="tv_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "season_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "time_left",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="season_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movie_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "time_left",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="movie_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "anime_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "time_left",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="anime_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "manga_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "time_left",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="manga_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "game_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "time_left",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="game_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "book_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "time_left",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="book_sort_valid",
            ),
        ),
    ]
