# Generated by Django 5.2.7 on 2025-11-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_home_sort_user_home_sort_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hide_from_search',
        ),
        migrations.AddField(
            model_name='user',
            name='clickable_media_cards',
            field=models.BooleanField(default=False, help_text='Hide hover overlay on touch devices'),
        ),
    ]
