# Generated by Django 5.2.7 on 2025-10-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_clickable_media_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_detail_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='list_detail_status_valid'),
        ),
    ]
