# Generated by Django 5.2.9 on 2026-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_item_title'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0040_user_list_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quick_watch_date',
            field=models.CharField(choices=[('current_date', 'Current Date'), ('release_date', 'Release Date'), ('no_date', 'No Date')], default='current_date', help_text='Date to use when bulk-marking media as completed', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('quick_watch_date__in', ['current_date', 'release_date', 'no_date'])), name='quick_watch_date_valid'),
        ),
    ]
