# Generated by Django 5.2.2 on 2025-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='User location (city, country)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, help_text='User preferred pronouns (e.g. she/her, he/him, they/them)', max_length=50),
        ),
    ]
