# Generated by Django 5.2.9 on 2026-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_add_quick_watch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(choices=[('Y-m-d', '2026-01-18 (ISO)'), ('d/m/Y', '18/01/2026 (EU)'), ('m/d/Y', '01/18/2026 (US)'), ('M j, Y', 'Jan 18, 2026')], default='Y-m-d', help_text='Preferred date display format', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='time_format',
            field=models.CharField(choices=[('H:i', '14:30 (24-hour)'), ('g:i A', '2:30 PM (12-hour)')], default='H:i', help_text='Preferred time display format', max_length=20),
        ),
    ]
