# Generated by Django 5.2.9 on 2026-01-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_item_title'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0041_add_quick_watch_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='tv_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='season_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='movie_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='anime_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='manga_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='game_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='book_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='anime_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='comic_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('created_at', 'Date Added')], default='score', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tv_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date', 'created_at'])), name='tv_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('season_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date', 'created_at'])), name='season_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('movie_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date', 'created_at'])), name='movie_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('anime_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date', 'created_at'])), name='anime_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('manga_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date', 'created_at'])), name='manga_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date', 'created_at'])), name='game_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('book_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date', 'created_at'])), name='book_sort_valid'),
        ),
    ]
