# Generated by Django 5.2.9 on 2026-02-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to fix boardgame value."""

    dependencies = [
        ("users", "0044_user_progress_bar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Boardgame"),
                ],
                default="tv",
                max_length=10,
            ),
        ),
    ]
