# Generated by Django 5.2.9 on 2026-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to show progress bar by default."""

    dependencies = [
        ("users", "0045_alter_user_last_search_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="progress_bar",
            field=models.BooleanField(default=True, help_text="Show progress bar"),
        ),
    ]
