# Generated by Django 5.2.9 on 2026-02-06 22:42

from django.db import migrations


def set_progress_bar_true(apps, schema_editor):
    """Set progress_bar to True for all existing users."""
    User = apps.get_model("users", "User")
    User.objects.update(progress_bar=True)


class Migration(migrations.Migration):
    """Data migration to enable progress bar for all existing users."""

    dependencies = [
        ("users", "0046_alter_user_progress_bar"),
    ]

    operations = [
        migrations.RunPython(set_progress_bar_true, migrations.RunPython.noop),
    ]
