# Generated by Django 5.2.11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add home_hidden_items M2M field."""

    dependencies = [
        ("users", "0047_set_progress_bar_true"),
        ("app", "0055_alter_item_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_hidden_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Items hidden from the home page",
                related_name="hidden_from_home_by",
                to="app.item",
            ),
        ),
    ]
