# Generated by Django on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_set_progress_bar_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_completed_recommendations',
            field=models.BooleanField(default=False, help_text='Hide completed media in recommendations'),
        ),
    ]
