# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for show_special_episodes user preference."""

    dependencies = [
        ("users", "0048_user_show_home_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_special_episodes",
            field=models.BooleanField(
                default=True,
                help_text="Show special episodes in In Progress",
            ),
        ),
    ]
