# Generated by Django on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_add_hide_completed_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_zero_rating',
            field=models.BooleanField(default=False, help_text='Hide zero ratings from media cards'),
        ),
    ]
