# Generated by Django 5.2.11 on 2026-02-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_add_hide_zero_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_provider_region',
            field=models.CharField(default='UNSET', help_text='Region to show watch providers for', max_length=5),
        ),
    ]
