# Generated by Django 5.2.11 on 2026-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_anime_hide_from_home_basicmedia_hide_from_home_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0050_user_watch_provider_region'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='home_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='home_sort',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('recent', 'Recent'), ('completion', 'Completion'), ('episodes_left', 'Episodes Left'), ('title', 'Title'), ('hidden', 'Hidden')], default='upcoming', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('home_sort__in', ['upcoming', 'recent', 'completion', 'episodes_left', 'title', 'hidden'])), name='home_sort_valid'),
        ),
    ]
