# Generated by Django 5.2.9 on 2025-12-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_user_watch_provider_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="obfuscate_unseen_episodes",
            field=models.BooleanField(
                default=False,
                help_text="Blur unseen episode images and descriptions",
            ),
        ),
    ]
