# Generated by GitHub Copilot on behalf of user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_user_watch_provider_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discovery_enabled",
            field=models.BooleanField(default=True, help_text="Show the Discovery section on the home page"),
        ),
    ]
