# Generated by Django 5.2.11 on 2026-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_user_watch_provider_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_special_episodes',
            field=models.BooleanField(default=True, help_text='Include Season 0 (Specials) in your In Progress list on the home page.'),
        ),
    ]
