# Generated by Django 5.2.13 on 2026-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_user_private_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='week_start_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', help_text='First day of the week', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('week_start_day__in', ['monday', 'sunday'])), name='week_start_day_valid'),
        ),
    ]
