# Generated by Django 5.2.13 on 2026-05-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_experience_experiencevisit_historicalexperience_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0053_user_private_profile_field"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="last_search_type_valid",
        ),
        migrations.AddField(
            model_name="user",
            name="experience_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_layout",
            field=models.CharField(
                choices=[("grid", "Grid"), ("table", "Table")],
                default="grid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="end_date",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Boardgame"),
                    ("experience", "Experience"),
                ],
                default="tv",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "experience",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
    ]
