# Generated by Django 5.2.13 on 2026-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_alter_item_image"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0054_remove_user_last_search_type_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="last_search_type_valid",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
    ]
