# Generated by Django 5.2 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_user_week_start_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jellyfin_mark_played_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Process Jellyfin MarkPlayed webhook events",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jellyfin_mark_unplayed_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Process Jellyfin MarkUnplayed webhook events",
            ),
        ),
    ]
