# Generated by Django 5.2 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_user_jellyfin_mark_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_hide_unreleased",
            field=models.BooleanField(
                default=False,
                help_text="Hide unreleased media from the home page",
            ),
        ),
    ]
