# Generated by Django 5.2.14 on 2026-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_user_jellyfin_mark_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_special_seasons',
            field=models.BooleanField(default=False, help_text='Hide special seasons (Season 0) from the home page'),
        ),
    ]
