# Generated by Django 5.2.7 on 2026-06-15 18:25

from django.db import migrations, models


def reset_boardgame_search_preference(apps, schema_editor):
    """Reset users whose last search media type was board games."""
    User = apps.get_model("users", "User")
    User.objects.filter(last_search_type="boardgame").update(last_search_type="tv")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_remove_boardgame_item_remove_boardgame_user_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0055_user_jellyfin_mark_events'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='last_search_type_valid',
        ),
        migrations.RunPython(
            reset_boardgame_search_preference,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='boardgame_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='boardgame_layout',
        ),
        migrations.RemoveField(
            model_name='user',
            name='boardgame_sort',
        ),
        migrations.RemoveField(
            model_name='user',
            name='boardgame_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic')], default='tv', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'movie', 'anime', 'manga', 'game', 'book', 'comic'])), name='last_search_type_valid'),
        ),
    ]
