# Generated by Django 5.2.16 on 2026-09-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_paid_providers',
            field=models.BooleanField(default=False, help_text='Show buy/rent watch providers in addition to no charge options'),
        ),
    ]
