# Generated by Django 5.2.16 on 2026-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_hide_unavailable_to_stream',
            field=models.BooleanField(default=False, help_text="Hide media that isn't available to stream from the home page"),
        ),
    ]
