# Generated by Django 5.2 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0056_user_home_hide_unreleased"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_export_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Prompt to export data automatically",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_export_interval_unit",
            field=models.CharField(
                choices=[
                    ("days", "Days"),
                    ("hours", "Hours"),
                    ("minutes", "Minutes"),
                    ("seconds", "Seconds"),
                ],
                default="days",
                help_text="Unit used for automatic export reminders",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_export_interval_value",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Number of units between automatic export reminders",
            ),
        ),
    ]
