# Generated by Django 5.2.16 on 2026-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_adult_titles',
            field=models.BooleanField(default=False, help_text='Show adult titles'),
        ),
    ]
