# Generated by Django 5.2.14 on 2026-07-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seerr_api_key',
            field=models.CharField(blank=True, default='', help_text='API key for your Seerr instance', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='seerr_url',
            field=models.URLField(blank=True, default='', help_text='URL of your Seerr instance (Overseerr/Jellyseerr)'),
        ),
    ]
