# Generated by Django 5.2 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_user_home_hide_unreleased"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="complete_season_on_last_episode",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Marking the last episode of a season as watched sets the "
                    "season as completed"
                ),
            ),
        ),
    ]
