# Generated by Django 5.2 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_user_home_hide_unreleased"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="include_specials",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Count specials towards TV show status and list them as seasons"
                ),
            ),
        ),
    ]
