# Generated by Django 5.2.16 on 2026-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_item_tmdb_rating_item_tmdb_rating_updated_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='tv_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='season_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='movie_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='anime_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='manga_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='game_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='book_sort_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='home_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='anime_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='boardgame_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='comic_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_sort',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('recent', 'Recent'), ('completion', 'Completion'), ('episodes_left', 'Episodes Left'), ('title', 'Title'), ('score', 'Rating'), ('tmdb_rating', 'TMDB Rating')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('tmdb_rating', 'TMDB Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('release_date', 'Release Date')], default='score', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('home_sort__in', ['upcoming', 'recent', 'completion', 'episodes_left', 'title', 'score', 'tmdb_rating'])), name='home_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tv_sort__in', ['score', 'tmdb_rating', 'title', 'progress', 'start_date', 'end_date', 'release_date'])), name='tv_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('season_sort__in', ['score', 'tmdb_rating', 'title', 'progress', 'start_date', 'end_date', 'release_date'])), name='season_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('movie_sort__in', ['score', 'tmdb_rating', 'title', 'progress', 'start_date', 'end_date', 'release_date'])), name='movie_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('anime_sort__in', ['score', 'tmdb_rating', 'title', 'progress', 'start_date', 'end_date', 'release_date'])), name='anime_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('manga_sort__in', ['score', 'tmdb_rating', 'title', 'progress', 'start_date', 'end_date', 'release_date'])), name='manga_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_sort__in', ['score', 'tmdb_rating', 'title', 'progress', 'start_date', 'end_date', 'release_date'])), name='game_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('book_sort__in', ['score', 'tmdb_rating', 'title', 'progress', 'start_date', 'end_date', 'release_date'])), name='book_sort_valid'),
        ),
    ]
