# Generated by Django 5.2.17 on 2026-10-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_adult_titles',
            field=models.BooleanField(default=True, help_text='Show adult titles in search results'),
        ),
    ]
