# Generated by Django 5.2.14 on 2026-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_hide_special_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hide_special_seasons',
            field=models.BooleanField(default=False, help_text='Hide special seasons (Season 0) from the home page'),
        ),
    ]
