from django.urls import path

from api.views.auth import (
    AppleAuthView,
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetView,
    RefreshView,
    RegisterView,
)
from api.views.diary import DiaryDetailView, DiaryLikeView, DiaryListView, DiaryTagsView
from api.views.health import HealthView, MetaView
from api.views.imports import (
    ExportCSVView,
    ImportScheduleView,
    ImportSourceView,
    ImportsView,
    ImportTaskView,
)
from api.views.lists import (
    ListCollaboratorDetailView,
    ListCollaboratorsView,
    ListDetailView,
    ListItemDetailView,
    ListItemsView,
    ListLikeView,
    ListsView,
)
from api.views.media import (
    CommunityStatsView,
    ManualMediaView,
    MediaDetailView,
    MediaDiscoverView,
    MediaSearchView,
    MediaSourcesView,
    SeasonDetailView,
    SeasonEpisodesView,
    TVSeasonsView,
)
from api.views.profile import (
    AvatarView,
    HOFItemView,
    MeHOFView,
    MeView,
    PreferencesView,
    PublicProfileView,
    UserHOFView,
    UserSearchView,
)
from api.views.social import (
    BlockView,
    FeedView,
    FollowRequestActionView,
    FollowRequestsView,
    FollowView,
    GenericLikeView,
    UserActivityView,
)
from api.views.stats import MyStatsSummaryView, UserStatsSummaryView
from api.views.tracking import (
    BookCompleteView,
    BookProgressView,
    EpisodeWatchView,
    SeasonStartView,
    SeasonWatchView,
    TrackingActionView,
    TrackingDetailView,
    TrackingListView,
    TVStartView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="api-health"),
    path("meta/", MetaView.as_view(), name="api-meta"),
    path("auth/register/", RegisterView.as_view(), name="api-register"),
    path("auth/login/", LoginView.as_view(), name="api-login"),
    path("auth/refresh/", RefreshView.as_view(), name="api-refresh"),
    path("auth/logout/", LogoutView.as_view(), name="api-logout"),
    path("auth/password-reset/", PasswordResetView.as_view(), name="api-password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmView.as_view(), name="api-password-reset-confirm"),
    path("auth/apple/", AppleAuthView.as_view(), name="api-apple"),
    path("me/", MeView.as_view(), name="api-me"),
    path("me/avatar/", AvatarView.as_view(), name="api-me-avatar"),
    path("me/preferences/", PreferencesView.as_view(), name="api-me-preferences"),
    path("me/hof/", MeHOFView.as_view(), name="api-me-hof"),
    path("me/hof/<str:media_type>/", HOFItemView.as_view(), name="api-me-hof-item"),
    path("media/search/", MediaSearchView.as_view(), name="api-media-search"),
    path("media/discover/", MediaDiscoverView.as_view(), name="api-media-discover"),
    path("media/sources/", MediaSourcesView.as_view(), name="api-media-sources"),
    path("media/manual/", ManualMediaView.as_view(), name="api-media-manual"),
    path("media/<str:source>/tv/<str:media_id>/seasons/", TVSeasonsView.as_view(), name="api-tv-seasons"),
    path("media/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/", SeasonDetailView.as_view(), name="api-season-detail"),
    path("media/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/episodes/", SeasonEpisodesView.as_view(), name="api-season-episodes"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/community/", CommunityStatsView.as_view(), name="api-media-community"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/", MediaDetailView.as_view(), name="api-media-detail"),
    path("tracking/", TrackingListView.as_view(), name="api-tracking-list"),
    path("tracking/<str:source>/tv/<str:media_id>/start/", TVStartView.as_view(), name="api-tv-start"),
    path("tracking/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/start/", SeasonStartView.as_view(), name="api-season-start"),
    path("tracking/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/watch/", SeasonWatchView.as_view(), name="api-season-watch"),
    path("tracking/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/episodes/<int:episode_number>/watch/", EpisodeWatchView.as_view(), name="api-episode-watch"),
    path("tracking/<str:source>/book/<str:media_id>/progress/", BookProgressView.as_view(), name="api-book-progress"),
    path("tracking/<str:source>/book/<str:media_id>/complete/", BookCompleteView.as_view(), name="api-book-complete"),
    path("tracking/<str:source>/<str:media_type>/<str:media_id>/actions/<str:action>/", TrackingActionView.as_view(), name="api-tracking-action"),
    path("tracking/<str:source>/<str:media_type>/<str:media_id>/", TrackingDetailView.as_view(), name="api-tracking-detail"),
    path("diary/", DiaryListView.as_view(), name="api-diary-list"),
    path("diary/tags/", DiaryTagsView.as_view(), name="api-diary-tags"),
    path("diary/<int:entry_id>/", DiaryDetailView.as_view(), name="api-diary-detail"),
    path("diary/<int:entry_id>/like/", DiaryLikeView.as_view(), name="api-diary-like"),
    path("stats/me/summary/", MyStatsSummaryView.as_view(), name="api-my-stats"),
    path("lists/", ListsView.as_view(), name="api-lists"),
    path("lists/<int:list_id>/", ListDetailView.as_view(), name="api-list-detail"),
    path("lists/<int:list_id>/items/", ListItemsView.as_view(), name="api-list-items"),
    path("lists/<int:list_id>/items/<int:item_id>/", ListItemDetailView.as_view(), name="api-list-item-detail"),
    path("lists/<int:list_id>/collaborators/", ListCollaboratorsView.as_view(), name="api-list-collaborators"),
    path("lists/<int:list_id>/collaborators/<int:user_id>/", ListCollaboratorDetailView.as_view(), name="api-list-collaborator-detail"),
    path("lists/<int:list_id>/like/", ListLikeView.as_view(), name="api-list-like"),
    path("feed/", FeedView.as_view(), name="api-feed"),
    path("follow-requests/", FollowRequestsView.as_view(), name="api-follow-requests"),
    path("follow-requests/<int:request_id>/<str:action>/", FollowRequestActionView.as_view(), name="api-follow-request-action"),
    path("social/likes/", GenericLikeView.as_view(), name="api-social-likes"),
    path("imports/", ImportsView.as_view(), name="api-imports"),
    path("imports/<str:source>/", ImportSourceView.as_view(), name="api-import-source"),
    path("imports/tasks/<str:task_id>/", ImportTaskView.as_view(), name="api-import-task"),
    path("imports/schedules/<int:schedule_id>/", ImportScheduleView.as_view(), name="api-import-schedule"),
    path("exports/csv/", ExportCSVView.as_view(), name="api-export-csv"),
    path("users/search/", UserSearchView.as_view(), name="api-user-search"),
    path("users/<str:username>/", PublicProfileView.as_view(), name="api-user-profile"),
    path("users/<str:username>/hof/", UserHOFView.as_view(), name="api-user-hof"),
    path("users/<str:username>/stats/summary/", UserStatsSummaryView.as_view(), name="api-user-stats"),
    path("users/<str:username>/activity/", UserActivityView.as_view(), name="api-user-activity"),
    path("users/<str:username>/follow/", FollowView.as_view(), name="api-user-follow"),
    path("users/<str:username>/block/", BlockView.as_view(), name="api-user-block"),
]
