# Generated by Django 5.2.9 on 2025-12-27 21:32

from django.db import migrations
from app.models import MediaTypes

def delete_empty_content_number_comic_events(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(
        item__media_type=MediaTypes.COMIC.value,
        content_number__isnull=True
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_delete_single_anime_events'),
    ]

    operations = [
        migrations.RunPython(delete_empty_content_number_comic_events),
    ]