name: App Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Run Tests
      env:
        YAMTRACK_SECRET: ${{ secrets.YAMTRACK_SECRET }}
        YAMTRACK_TMDB_API: ${{ secrets.YAMTRACK_TMDB_API }}
        YAMTRACK_MAL_API: ${{ secrets.YAMTRACK_MAL_API }}
      run: |
        coverage run --source='src/app' --parallel-mode src/manage.py test app

    - name: Build Coverage Report
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}