name: App Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Run Tests
      env:
        SECRET: ${{ secrets.SECRET }}
        TMDB_API: ${{ secrets.TMDB_API }}
        MAL_API: ${{ secrets.MAL_API }}
      run: |
        coverage run --source='src/app' --parallel-mode src/manage.py test app
        coverage run --source='src/users' --parallel-mode src/manage.py test users
        coverage run --source='src/integrations' --parallel-mode src/manage.py test integrations

    - name: Build Coverage Report
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}