name: App Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Run Tests
      env:
        SECRET: ${{ secrets.SECRET }}
        TMDB_API: ${{ secrets.TMDB_API }}
        MAL_API: ${{ secrets.MAL_API }}
        ADMIN_ENABLED: True
      run: |
        coverage run --source='src/app' --parallel-mode src/manage.py test app.tests.test_views
        coverage run --source='src/app' --parallel-mode src/manage.py test app.tests.test_media
        coverage run --source='src/app' --parallel-mode src/manage.py test app.tests.test_imports
        coverage run --source='src/app' --parallel-mode src/manage.py test app.tests.test_forms

    - name: Build Coverage Report
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}